name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish Build
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Publish library
        env:
          GA_USER: ${{ secrets.GA_USER }}
          GA_TOKEN: ${{ secrets.GA_TOKEN }}
        run: ./gradlew publish